### ISSUE TITLE
update setting, don't change value and create a new setting

### ISSUE THREAD

**Issue by Mabol** [Jako/CrossContextsSettings#2]
Hello and thanks for CCS
Modx 303, php 8 CCS 123

After creating a setting if I want to edit it, the following happens:
if i change area, namespace or filed type, nothing change
If I change the key it creates another setting.

The name of setting now is not avialable?

![Clipboard01](https://user-images.githubusercontent.com/5990867/224204223-8e7a18a7-800b-40b4-a924-5238ac6b0abf.jpg)

Thanks

**Comment by Jako** [comment]
I can't reproduce that issue with PHP 8.0, 8.1 and 8.2. Are there any warnings in the PHP error log? Or something in the MODX error log?

**Comment by Mabol** [comment]
Nothing, only in console but every time i opne the tab for create or update:
Uncaught TypeError: Ext.getCmp(...) is undefined
    CreateUpdateContextsSetting http://modx303.loc/assets/components/crosscontextssettings/js/mgr/crosscontextssettings.min.js?v=v1.2.3:6
 width no php error, warning or deprecate
![immagine](https://user-images.githubusercontent.com/5990867/224429905-0896d066-d992-4b9c-993c-2058957cce18.png)

**Comment by Jako** [comment]
Ext.getCmp is a default core ExtJS method. There must be something very weird in your installation.

Can you extend the minified code (crosscontextssettings.min.js) in the browser and post the code around this line to see where this happens.

**Comment by Mabol** [comment]
In this point there is a segnalation:
listeners:{afterrender:function(){Ext.getCmp("modx-filter-namespace").hide()}}

i know that Ex.getCmp there is a defualt method but this console error arrive only when i open CrossCS, i dont' Know :)

If i delete the above line, in edit no error but in create the error is in:
this.setValues({namespace:Ext.getCmp("modx-filter-namespace").value

i think the "my" problem is in  modx-filter-namespace

but this is the problem because if i edit the key of setting, create a new setting and other change don't have effect?

**Comment by Jako** [comment]
What user is logged in there? The default sudo admin user? Or is this user restricted somehow?

**Comment by Mabol** [comment]
Only sudo admin user
No ACL or group Resource or Group Users, created

**Comment by Jako** [comment]
Fuck! Someone removed `id: 'modx-filter-namespace'` in 3.0.3. All my extras with a dedicated system settings tab have issues with that version.

**Comment by Jako** [comment]
But this does not destroy changing the values in the context settings grid.

**Comment by Jako** [comment]
This is solved with 1.2.4. The setting key can't be changed anymore since that's not possible in the settings of a context too.
